version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PGDATABASE=reposcope
      - PGUSER=reposcope_user
      - PGPASSWORD=reposcope_password
      - PGHOST=db
      - PGPORT=5432
      - SECRET_KEY=your-development-secret-key
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=reposcope
      - POSTGRES_USER=reposcope_user
      - POSTGRES_PASSWORD=reposcope_password

volumes:
  postgres_data: 